<?php

/**
 * @file
 * Contains unicef42.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
	function unicef42_help($route_name, RouteMatchInterface $route_match) {
	  	switch ($route_name) {
		    // Main module help for the unicef42 module.
		    case 'help.page.unicef42':
			      $output = '';
			      $output .= '<h3>' . t('About') . '</h3>';
			      $output .= '<p>' . t('Module pour accèder aux souvenirs') . '</p>';
			      return $output;

	    default:
	    }
}


function unicef42_theme() {
  		return array(
        'world' => array(
            'template' => 'world',
            'variables' => array('texte' => NULL)
        ),
    );
	}

