<?php

/**
 * @file
 * Contains unicef42.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 * /site/admin/help/unicef42
 */
	function unicef42_help($route_name, RouteMatchInterface $route_match) {
	  	switch ($route_name) {
		    // Main module help for the unicef42 module.
		    case 'help.page.unicef42':
			      $output = '';
			      $output .= '<h3>' . t('About') . '</h3>';
			      $output .= '<p>' . t('Module pour accèder aux souvenirs') . '</p>';
			      return $output;

	    default:
	    }
}


function unicef42_theme() {
  		return array(
        'world' => array(
            'template' => 'world',
            'variables' => array('values' => NULL)
        ),
        'pbroute' => array(
            'template' => 'pbroute',
            'variables' => array(
                'values' => NULL,
                'donnees' => NULL,
                'key' => NULL
                )
        ),
        'fetes' => array(
            'template' => 'fetes',
            'variables' => array('texte' => NULL)
        ),
        'temps-periscolaire' => array(
            'template' => 'temps-periscolaire',
            'variables' => array('texte' => NULL)
        ),
        'jeunes-ambasadeurs' => array(
            'template' => 'jeunes-ambasadeurs',
            'variables' => array('texte' => NULL)
        ),
        'frimousses' => array(
            'template' => 'frimousses',
            'variables' => array('texte' => NULL)
        ),
        'ecoles' => array(
            'template' => 'ecoles',
            'variables' => array('texte' => NULL)
        ),
        'clubs-jeunes' => array(
            'template' => 'clubs-jeunes',
            'variables' => array('texte' => NULL)
        ),
        'centres-sociaux' => array(
            'template' => 'centres-sociaux',
            'variables' => array('texte' => NULL)
        ),
        'actions-solidaires' => array(
            'template' => 'actions-solidaires',
            'variables' => array('texte' => NULL)
        ),
        'droits-dans-l-ecole' => array(
            'template' => 'droits-dans-l-ecole',
            'variables' => array('texte' => NULL)
        ),
        'manif-sportive' => array(
            'template' => 'manif-sportive',
            'variables' => array('texte' => NULL)
        ),
        'festivals' => array(
            'template' => 'festivals',
            'variables' => array('texte' => NULL)
        ),
        'accueil' => array(
            'template' => 'accueil',
            'variables' => array('texte' => NULL)
        ),

    );
	}

