<?php

/**
 * @file
 * Contains scotts_module.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function scotts_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the scotts_module module.
    case 'help.page.scotts_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

